Initialize()
Stage()
Note(noteTime = 1.0)
Note(noteTime = 2.0)
Note(noteTime = 3.0)
Note(noteTime = 4.0)
Note(noteTime = 4.5)
Note(noteTime = 5.0)
Note(noteTime = 5.5)
Note(noteTime = 6.0)
Note(noteTime = 6.25)
Note(noteTime = 6.5)
Note(noteTime = 6.75)
Note(noteTime = 7.0)